# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3a1511b3dbca03d78ad0dbfc3cadd80659882a7f97ea5f1440ce5354993ca24dbbd3598084c381c3263dcbdf19db93bf2d155d503aab4a68fad98106d6d8766

test:
  secret_key_base: 4e8429a5dcfd1e4b125a1851e80df362d6adb71d113e0fb862cd26cbbceb53471fb1e1b4592a4424819d910e3db16eda791a3ea2e3cdd2576b94743e31a78db5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
